CREATE TABLE IF NOT EXISTS admin_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS service_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS services (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_slug TEXT NOT NULL,
  name TEXT NOT NULL,
  short_description TEXT,
  long_description TEXT,
  price INTEGER NOT NULL,
  price_max INTEGER,
  duration_minutes INTEGER NOT NULL,
  image_data TEXT,
  age_groups TEXT,
  active INTEGER DEFAULT 1,
  featured INTEGER DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  short_description TEXT,
  long_description TEXT,
  price INTEGER NOT NULL,
  rating DOUBLE PRECISION DEFAULT 5,
  image_data TEXT,
  stock INTEGER DEFAULT 999,
  active INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS bookings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id INTEGER,
  service_name TEXT,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  booking_date TEXT NOT NULL,
  booking_time TEXT NOT NULL,
  status TEXT DEFAULT 'pendiente',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS blocked_dates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT UNIQUE NOT NULL,
  reason TEXT,
  full_day INTEGER DEFAULT 1
);
CREATE TABLE IF NOT EXISTS testimonials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  text TEXT NOT NULL,
  rating DOUBLE PRECISION DEFAULT 5,
  active INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS gallery (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_data TEXT NOT NULL,
  caption TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS settings (
  "key" TEXT PRIMARY KEY,
  value TEXT
);

CREATE OR REPLACE FUNCTION public.aquazen_sql(q text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result jsonb;
  trimmed text := btrim(q);
BEGIN
  IF trimmed ~* '^[[:space:]]*(select|with)[[:space:]]' THEN
    EXECUTE 'SELECT COALESCE(jsonb_agg(row_to_json(t)), ''[]''::jsonb) FROM (' || q || ') t' INTO result;
    RETURN COALESCE(result, '[]'::jsonb);
  ELSIF trimmed ~* 'returning' THEN
    EXECUTE 'WITH t AS (' || q || ') SELECT COALESCE(jsonb_agg(row_to_json(t)), ''[]''::jsonb) FROM t' INTO result;
    RETURN COALESCE(result, '[]'::jsonb);
  ELSE
    EXECUTE q;
    RETURN '[]'::jsonb;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.aquazen_sql(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.aquazen_sql(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aquazen_sql(text) TO postgres;
